import { motion } from "motion/react"; import { ArrowDown, ArrowUpRight, Menu, X } from "lucide-react"; import { useState } from "react"; import { Button } from "./components/ui/button"; import { AnimatedText } from "./components/AnimatedText";

const services=[["Vehicle Sales","Find your next vehicle with 846 Autos.","/images/vehicle.jpg"],["Clearing & Forwarding","Moving vehicles and cargo with a service-first approach.","/images/logistics.jpg"],["Car Wash","Professional vehicle care for everyday and special rides.","/images/car-wash.jpg"],["Lounge & Bar","A space to unwind, connect and enjoy the moment.","/images/lounge.jpg"],["Snooker","Relax, play and make the most of your time with us.","/images/snooker.jpg"]];

function Section({children,className=""}){return <section className={"mx-auto w-full max-w-7xl px-5 py-24 md:px-8 md:py-32 "+className}>{children}</section>}

export default function App(){const [open,setOpen]=useState(false);return <div className="overflow-hidden bg-[#080808] text-white">
<header className="fixed inset-x-0 top-0 z-50"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 md:px-8"><a href="#" className="text-lg font-black tracking-[-.04em]">846<span className="text-white/40">.</span></a><nav className="hidden items-center gap-8 text-sm text-white/70 md:flex"><a href="#services" className="hover:text-white">Services</a><a href="#vehicles" className="hover:text-white">Vehicles</a><a href="#experience" className="hover:text-white">Experience</a><a href="#contact" className="hover:text-white">Contact</a></nav><button onClick={()=>setOpen(!open)} className="rounded-full border border-white/15 bg-black/30 p-3 backdrop-blur-md md:hidden">{open?<X size={18}/>:<Menu size={18}/>}</button></div>{open&&<div className="mx-4 rounded-2xl border border-white/10 bg-black/90 p-5 backdrop-blur-xl md:hidden"><div className="grid gap-4 text-lg"><a onClick={()=>setOpen(false)} href="#services">Services</a><a onClick={()=>setOpen(false)} href="#vehicles">Vehicles</a><a onClick={()=>setOpen(false)} href="#experience">Experience</a><a onClick={()=>setOpen(false)} href="#contact">Contact</a></div></div>}</header>

<main>
<section className="relative flex min-h-[92svh] items-end overflow-hidden border-b border-white/10"><div className="absolute inset-0 bg-[radial-gradient(circle_at_70%_20%,rgba(255,255,255,.18),transparent_30%),linear-gradient(180deg,rgba(0,0,0,.18),#080808)]"/><div className="absolute inset-0 bg-[url('/images/hero.jpg')] bg-cover bg-center opacity-75"/><div className="absolute inset-0 bg-gradient-to-t from-[#080808] via-[#080808]/25 to-transparent"/><Section className="relative z-10 pb-16 pt-40 md:pb-24"><p className="mb-6 text-xs font-semibold uppercase tracking-[.3em] text-white/55">846 Autos Limited</p><h1 className="max-w-5xl text-[clamp(3.5rem,9vw,8.5rem)] font-semibold leading-[.86] tracking-[-.07em]">More than<br/>just <AnimatedText words={["automotive.","mobility.","lifestyle.","experience."]}/></h1><div className="mt-10 flex flex-col gap-4 sm:flex-row"><Button onClick={()=>document.querySelector("#services")?.scrollIntoView({behavior:"smooth"})}>Explore 846 <ArrowDown size={16} className="ml-2"/></Button><Button variant="outline">Contact us <ArrowUpRight size={16} className="ml-2"/></Button></div></Section></section>

<Section><motion.div initial={{opacity:0,y:30}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{duration:.7}}><p className="text-sm uppercase tracking-[.25em] text-white/40">The 846 approach</p><h2 className="mt-5 max-w-4xl text-4xl font-medium tracking-[-.04em] md:text-6xl">One destination for movement, care, connection and good times.</h2></motion.div></Section>

<Section id="services" className="pt-8"><div className="mb-12 flex items-end justify-between"><div><p className="text-sm uppercase tracking-[.25em] text-white/40">What we do</p><h2 className="mt-3 text-4xl font-medium tracking-[-.04em] md:text-6xl">Our services</h2></div></div><div className="grid gap-4 md:grid-cols-2">{services.map(([name,desc,img],i)=><motion.article key={name} initial={{opacity:0,y:35}} whileInView={{opacity:1,y:0}} viewport={{once:true,margin:"-80px"}} transition={{delay:i*.08,duration:.65}} className="group relative min-h-[360px] overflow-hidden rounded-3xl border border-white/10 bg-white/[.03] p-7 md:min-h-[440px]"><div className="absolute inset-0 bg-gradient-to-t from-black via-black/25 to-transparent"/><div className="absolute inset-0 bg-white/[.04] transition duration-700 group-hover:scale-105 group-hover:bg-white/[.08]"/><div className="relative z-10 flex h-full flex-col justify-end"><span className="mb-auto text-sm text-white/35">0{i+1}</span><h3 className="text-3xl font-medium tracking-[-.03em]">{name}</h3><p className="mt-3 max-w-md text-white/55">{desc}</p><a href="#contact" className="mt-6 inline-flex w-fit items-center text-sm font-medium">Learn more <ArrowUpRight size={16} className="ml-2 transition-transform group-hover:translate-x-1 group-hover:-translate-y-1"/></a></div></motion.article>)}</div></Section>

<Section id="vehicles" className="border-y border-white/10"><div className="grid gap-12 md:grid-cols-[.8fr_1.2fr] md:items-end"><div><p className="text-sm uppercase tracking-[.25em] text-white/40">Vehicles</p><h2 className="mt-4 text-5xl font-medium tracking-[-.05em] md:text-7xl">Drive something worth remembering.</h2></div><div className="text-white/55 md:pb-2"><p>Our vehicle showcase will be connected to verified inventory as the project moves from demo to production.</p></div></div></Section>

<Section id="experience"><div className="rounded-[2rem] border border-white/10 bg-white/[.03] p-8 md:p-14"><p className="text-sm uppercase tracking-[.25em] text-white/40">Beyond the road</p><div className="mt-10 grid gap-10 md:grid-cols-2"><h2 className="text-5xl font-medium tracking-[-.05em] md:text-7xl">Stay a little longer.</h2><p className="max-w-lg self-end text-lg leading-relaxed text-white/55">From the car wash to the lounge and snooker, 846 brings automotive and lifestyle experiences together in one place.</p></div></div></Section>

<Section id="contact" className="pb-20"><div className="rounded-[2rem] bg-white p-8 text-black md:p-16"><p className="text-sm uppercase tracking-[.25em] text-black/45">Start a conversation</p><h2 className="mt-5 max-w-3xl text-5xl font-medium tracking-[-.05em] md:text-7xl">Ready when you are.</h2><div className="mt-10"><Button className="bg-black text-white hover:bg-black/90">Contact 846 Autos <ArrowUpRight size={16} className="ml-2"/></Button></div></div></Section>
</main><footer className="border-t border-white/10 px-5 py-8 md:px-8"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-4 text-sm text-white/40 md:flex-row"><span>846 Autos Limited</span><span>Demo experience — 2026</span></div></footer></div>}